---
- name: Deploy dbsentinel
  hosts: dbservers
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - git
          - python3
        state: present
    - name: Create /opt/db-sentinel
      ansible.builtin.file:
        path: /opt/db-sentinel
        state: directory
        mode: '0755'
    - name: Clone repo
      ansible.builtin.git:
        repo: https://github.com/witcliff-byte/db-sentinel.git
        dest: /opt/db-sentinel
        accept_hostkey: true

